name: Check plugin versions
on:
  schedule:
    - cron: "*/20 * * * *"   # every 20 minutes
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install -r requirements.txt
      - run: python check_versions.py
      - name: Commit timestamp update
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add versions.yml
          git diff --staged --quiet || git commit -m "Update last_checked timestamp"
          git push
