#!/usr/bin/env python3
import json, urllib.request, yaml

with open("versions.yml") as f:
    data = yaml.safe_load(f)

outdated = []
for name, meta in data["plugins"].items():
    url = meta["repo"]
    current = str(meta["current"]).lstrip("v")
    latest = json.load(urllib.request.urlopen(url))["tag_name"].lstrip("v")
    if latest != current:
        outdated.append(f"{name}: {current} -> {latest}")

if outdated:
    print("Updates available:\n" + "\n".join(outdated))
    raise SystemExit(1)
else:
    print("All plugins up to date.")
